-- Generated by N1kaa x 79xv
-- Target: Cultivation Simulator

local VirtualUser = game:GetService("VirtualUser")
local Player = game:GetService("Players").LocalPlayer

-- [ANTI-AFK MODULE]
game:GetService("Players").LocalPlayer.Idled:connect(function()
   VirtualUser:CaptureController()
   VirtualUser:ClickButton2(Vector2.new())
   print("Anti-AFK: Prevented idle kick")
end)

-- [IDLE TIMER]
while wait(900) do
    print("Script Active: 15m check cycle")
    -- Keep alive ping
end
